#!/bin/sh
# PreToolUse guard for Edit/Write/NotebookEdit.
#
# Enforces AGENTS.md hard rules #1 (never edit generated .flow.js) and #6
# (never commit secrets) deterministically, instead of relying on the model
# having read the docs.
#
# Exit 2 = block the tool call and hand stderr back to Claude as feedback.
# Exit 0 = allow.
set -eu

path=$(jq -r '.tool_input.file_path // empty' 2>/dev/null || true)
[ -n "$path" ] || exit 0

block() {
  echo "BLOCKED: $path" >&2
  echo "$1" >&2
  exit 2
}

case "$path" in
  # Templates and samples are the editable counterparts — always allowed.
  *.env.sample | *.env.example | *.dev.vars.example)
    exit 0
    ;;

  *.flow.js)
    block "This file is generated by flowmark from the sibling .flow template.
Edit ${path%.js} instead — the compile-flow hook will regenerate this file."
    ;;

  *.env | *.env.local | *.env.*.local | *.dev.vars)
    block "Local secrets file (gitignored). Add the key to .env.sample with a
placeholder value and let the user fill in the real secret themselves."
    ;;

  */dist/* | */.nx/* | */.wrangler/* | */node_modules/* | */.angular/*)
    block "Build output / tooling cache. Change the source that produces it."
    ;;

  *pnpm-lock.yaml)
    block "Lockfiles are generated. Run 'pnpm install' instead — CI fails the
build if pnpm-lock.yaml does not match a clean install."
    ;;

  *data/*.db)
    block "Local SQLite database. Change the schema in code and re-seed
('pnpm seed:user') rather than editing the .db file."
    ;;
esac

exit 0
