import { renderValue } from '@flowview/runtime';

export function render(context) {
  let output = '';
  output += '<and-card variant="elevated" padded and-layout="vertical gap:md" and-motion="fade-in slide-in-up" and-motion-trigger="enter" and-motion-duration="600ms">\n\n  <div and-layout="horizontal justify:center align:center gap:sm">\n    <and-icon name="lock" size="24"></and-icon>\n    <span and-text="h6 weight:bold color:foreground">DevAuth</span>\n  </div>\n\n  <div and-layout="vertical gap:xs">\n    <h1 and-text="h4 align:center color:foreground">Authorize application</h1>\n    <p and-text="p-sm align:center color:muted">\n      <span id="client-name">An application</span> wants to sign you in.\n    </p>\n  </div>\n\n  <div and-layout="vertical gap:xs">\n    <span and-text="p-xs color:foreground weight:medium">It will be able to read</span>\n    <ul id="scope-list" and-text="p-sm color:muted" style="margin:0;padding-left:1.25rem"></ul>\n  </div>\n\n  <div and-layout="vertical gap:sm">\n    <and-button id="allow-btn" variant="default" data-full>\n      <and-icon slot="start" name="check" size="16"></and-icon>\n      Allow\n    </and-button>\n    <and-button id="deny-btn" variant="outline" data-full>\n      Cancel\n    </and-button>\n  </div>\n</and-card>';
  output += '\n\n<script type="module">\n  (function() {\n    const allowBtn = document.getElementById(\'allow-btn\');\n    const denyBtn = document.getElementById(\'deny-btn\');\n    const toaster = document.getElementById(\'toaster\');\n\n    // The provider signs the authorization request into this page\'s query\n    // string and verifies that signature when the decision comes back, so the\n    // whole string is forwarded verbatim — re-assembling it from parts would\n    // invalidate it.\n    const oauthQuery = window.location.search.replace(/^\\?/, \'\');\n    const params = new URLSearchParams(oauthQuery);\n\n    const clientId = params.get(\'client_id\');\n    if (clientId) {\n      // textContent, not innerHTML: client_id arrives in the URL.\n      document.getElementById(\'client-name\').textContent = clientId;\n    }\n\n    const SCOPE_LABELS = {\n      openid: \'Who you are (a stable account identifier)\',\n      profile: \'Your name and avatar\',\n      email: \'Your email address\',\n      offline_access: \'Stay signed in when you are away\'\n    };\n\n    const list = document.getElementById(\'scope-list\');\n    (params.get(\'scope\') || \'\').split(\' \').filter(Boolean).forEach(function(scope) {\n      const item = document.createElement(\'li\');\n      item.textContent = SCOPE_LABELS[scope] || scope;\n      list.appendChild(item);\n    });\n\n    async function decide(accept, button) {\n      button.loading = true;\n\n      try {\n        const res = await fetch(\'/api/auth/oauth2/consent\', {\n          method: \'POST\',\n          headers: { \'Content-Type\': \'application/json\' },\n          credentials: \'include\',\n          body: JSON.stringify({ accept: accept, oauth_query: oauthQuery })\n        });\n\n        const data = await res.json();\n\n        if (!res.ok || !data.redirect_uri) {\n          throw new Error(data.message || data.error_description || data.error || \'Could not complete authorization\');\n        }\n\n        window.location.href = data.redirect_uri;\n      } catch (err) {\n        button.loading = false;\n        toaster.present(err.message || \'Could not complete authorization\', \'error\');\n      }\n    }\n\n    allowBtn.addEventListener(\'click\', function() { decide(true, allowBtn); });\n    denyBtn.addEventListener(\'click\', function() { decide(false, denyBtn); });\n  })();\n</script>\n';

  return output;
}
