import { renderValue } from '@flowview/runtime';

export function render(context) {
  let output = '';
  output += '<and-card variant="elevated" padded and-layout="vertical gap:md" and-motion="fade-in slide-in-up" and-motion-trigger="enter" and-motion-duration="600ms" and-motion-delay="100ms">\n\n  <div and-layout="horizontal justify:center align:center gap:sm">\n    <and-icon name="lock" size="24"></and-icon>\n    <span and-text="h6 weight:bold color:foreground">DevFlare Auth</span>\n  </div>\n\n  <div and-layout="vertical gap:xs">\n    <h1 and-text="h4 align:center color:foreground">Forgot password?</h1>\n    <p and-text="p-sm align:center color:muted">Enter your email and we\'ll send you a reset link</p>\n  </div>\n\n  <form id="forgot-form" and-layout="vertical gap:sm">\n    <div and-layout="vertical gap:xs">\n      <label for="email" and-text="p-xs color:foreground weight:medium">Email</label>\n      <div and-layout="horizontal gap:sm align:center">\n        <and-icon name="mail" size="16" color="hsl(var(--muted-foreground))"></and-icon>\n        <and-input id="email" data-field="email" type="email" placeholder="you@example.com" required style="flex:1">\n        </and-input>\n      </div>\n    </div>\n\n    <and-button id="submit-btn" type="submit" variant="default" style="width: 100%;">\n      <and-icon slot="start" name="arrow-right" size="16"></and-icon>\n      Send Reset Link\n    </and-button>\n  </form>\n\n  <p and-text="p-sm align:center color:muted">\n    Remember your password? <a href="/login">Sign in</a>\n  </p>\n</and-card>';
  output += '\n\n<script>\n  (function() {\n    const form = document.getElementById(\'forgot-form\');\n    const submitBtn = document.getElementById(\'submit-btn\');\n    const toaster = document.getElementById(\'toaster\');\n    const values = {};\n\n    form.querySelectorAll(\'and-input[data-field]\').forEach(function(input) {\n      input.addEventListener(\'andInput\', function(e) {\n        values[input.dataset.field] = e.detail;\n      });\n    });\n\n    form.addEventListener(\'submit\', async function(e) {\n      e.preventDefault();\n\n      const email = (values.email || \'\').trim();\n\n      if (!email) {\n        toaster.present(\'Please enter your email\', \'destructive\');\n        return;\n      }\n\n      submitBtn.loading = true;\n\n      try {\n        const res = await fetch(\'/api/auth/forget-password\', {\n          method: \'POST\',\n          headers: { \'Content-Type\': \'application/json\' },\n          credentials: \'include\',\n          body: JSON.stringify({ email })\n        });\n\n        const data = await res.json();\n\n        if (!res.ok) {\n          throw new Error(data.message || data.error || \'Failed to send reset link\');\n        }\n\n        toaster.present(\'If an account exists, a reset link has been sent.\', \'success\');\n      } catch (err) {\n        toaster.present(\'If an account exists, a reset link has been sent.\', \'success\');\n      } finally {\n        submitBtn.loading = false;\n      }\n    });\n  })();\n</script>\n';

  return output;
}
