import {
  ApplicationConfig,
  importProvidersFrom,
  provideBrowserGlobalErrorListeners,
  provideZonelessChangeDetection,
} from '@angular/core';
import { withComponentInputBinding } from '@angular/router';
import { provideFileRouter } from '@analogjs/router';
import {
  LucideAngularModule,
  AlertCircle,
  ArrowLeft,
  ArrowRightLeft,
  Brush,
  Check,
  Circle,
  CircleCheck,
  CircleDashed,
  CircleX,
  Cloud,
  Copy,
  Download,
  ExternalLink,
  Globe,
  Image,
  Info,
  KeyRound,
  Link,
  Loader,
  Lock,
  Monitor,
  PaintBucket,
  Palette,
  Pencil,
  Plus,
  Power,
  QrCode,
  Radar,
  RefreshCw,
  Search,
  ShieldCheck,
  Square,
  Stethoscope,
  Terminal,
  Trash2,
  TriangleAlert,
  Upload,
  Video,
  X,
} from 'lucide-angular';

/**
 * Deliberately small: no HTTP client, no error reporting, no animation runtime,
 * and no identity provider at the app level. DevAuth is loaded only by the two
 * connected tool pages (src/app/connected/), so local tools stay anonymous and
 * make no request to DevTools' server. Changes here need a reason recorded in
 * apps/devtools/README.md.
 */
export const appConfig: ApplicationConfig = {
  providers: [
    provideZonelessChangeDetection(),
    provideBrowserGlobalErrorListeners(),
    provideFileRouter(withComponentInputBinding()),
    importProvidersFrom(
      LucideAngularModule.pick({
        AlertCircle,
        ArrowLeft,
        ArrowRightLeft,
        Brush,
        Check,
        Circle,
        CircleCheck,
        CircleDashed,
        CircleX,
        Cloud,
        Copy,
        Download,
        ExternalLink,
        Globe,
        Image,
        Info,
        KeyRound,
        Link,
        Loader,
        Lock,
        Monitor,
        PaintBucket,
        Palette,
        Pencil,
        Plus,
        Power,
        QrCode,
        Radar,
        RefreshCw,
        Search,
        ShieldCheck,
        Square,
        Stethoscope,
        Terminal,
        Trash2,
        TriangleAlert,
        Upload,
        Video,
        X,
      }),
    ),
  ],
};
