import {
  ApplicationConfig,
  provideZonelessChangeDetection,
} from '@angular/core';
import { provideRouter, withComponentInputBinding } from '@angular/router';
import { provideHttpClient } from '@angular/common/http';
import { importProvidersFrom } from '@angular/core';
import {
  LucideAngularModule,
  LayoutDashboard,
  Zap,
  FolderOpen,
  Image,
  QrCode,
  PanelLeftOpen,
  PanelLeftClose,
  Menu,
  Wrench,
  Upload,
  Download,
  Check,
  Loader,
  Plus,
  LogOut,
  User,
  Scissors,
  Search,
  Copy,
  Globe,
  Monitor,
  Video,
  FileJson,
  ArrowRightLeft,
  Brush,
  PaintBucket,
  PaintRoller,
  AlertCircle,
  ArrowLeft,
  Circle,
  Database,
  Github,
  Link,
  ExternalLink,
  Palette,
  Square,
  X,
  Settings,
} from 'lucide-angular';
import { appRoutes } from './app.routes';

export const appConfig: ApplicationConfig = {
  providers: [
    provideZonelessChangeDetection(),
    provideRouter(appRoutes, withComponentInputBinding()),
    provideHttpClient(),
    importProvidersFrom(
      LucideAngularModule.pick({
        LayoutDashboard,
        Zap,
        FolderOpen,
        Image,
        QrCode,
        PanelLeftOpen,
        PanelLeftClose,
        Menu,
        Wrench,
        Upload,
        Download,
        Check,
        Loader,
        Plus,
        LogOut,
        User,
        Scissors,
        Search,
        Copy,
        Globe,
        Monitor,
        Video,
        FileJson,
        ArrowRightLeft,
        Brush,
        PaintBucket,
        PaintRoller,
        AlertCircle,
        ArrowLeft,
        Circle,
        Database,
        Github,
        Link,
        ExternalLink,
        Palette,
        Square,
        X,
        Settings,
      }),
    ),
  ],
};
